### ISSUE TITLE
to_dict() does not convert enums to strings

### ISSUE THREAD

**Issue by supermihi** [lidatong/dataclasses-json#240]
As resolved in #51, python enums can be used with dataclasses-json and I have successfully tried that, using the `to_json()` and `from_json()` methods.

However, with `to_dict()`, enum values appear to be untouched, hence the resulting dictionary is not JSON serializable. I assume that this is *not* the intended behavior, as according to the [API docs](https://lidatong.github.io/dataclasses-json/reference/dataclasses_json/api/#to_dict), `to_dict()` should return a JSON-compatible dict.

**Comment by RunOrVeith** [comment]
Duplicate of #229

**Comment by lidatong** [comment]
Should be resolved by #229

**Comment by supermihi** [comment]
Thanks. I have upgrade to dataclasses-json 0.5.2, but the issue still persists.

**Comment by supermihi** [comment]
Minimal example:
```python
def test_serialize_enum():
    class TestEnum(Enum):
        A = 'a'
        B = 'b'
    @dataclass_json
    @dataclass
    class Data:
        bar: TestEnum

    foo = Data(TestEnum.A)
    assert isinstance(foo.to_dict()['bar'], str)
```

**Comment by RunOrVeith** [comment]
you have to do `foo.to_dict(encode_json=True)`

**Comment by supermihi** [comment]
Thanks!

**Comment by illeatmyhat** [comment]
I also have this issue with `to_json()`, which doesn't have an `encode_json` parameter.
What I ended up doing was 
```python3
from dataclasses import dataclass, field
from dataclasses_json import DataClassJsonMixin, config
from enum import Enum
class MyEnum(Enum):
    Foo = "foo"
    Bar = "bar"

@dataclass
class Data(DataClassJsonMixin):
    test: MyEnum = field(metadata=config(encoder=lambda x: x.value, decoder=MyEnum))

foo = Data(MyEnum.Foo)
print(foo.to_json())
assert Data.from_json('{"test": "foo"}').test == MyEnum.Foo
```
